/* ═══════════════════════════════════════════════════════════════
   data.js — Dados estáticos: exercícios, alimentos, constantes
════════════════════════════════════════════════════════════════ */

const EX = [
  {id:1,name:'Supino Reto',cat:'Peito',icon:'bx-dumbbell',desc:'Com barra, halteres, maquina ou Smith. Base pesada para peitoral, triceps e deltoides.',sets:4,reps:'8-12',active:40,rest:90,diff:'Intermédiário',muscles:'Peitoral, Triceps, Deltoides'},
  {id:2,name:'Supino Inclinado',cat:'Peito',icon:'bx-dumbbell',desc:'Variação para a porcao superior do peitoral, com barra, halteres, maquina ou Smith.',sets:4,reps:'8-12',active:40,rest:90,diff:'Intermédiário',muscles:'Peitoral superior, Triceps, Ombros'},
  {id:3,name:'Supino Declinado',cat:'Peito',icon:'bx-dumbbell',desc:'Variação para a porcao inferior do peitoral, com barra, halteres, maquina ou Smith.',sets:4,reps:'8-12',active:40,rest:90,diff:'Intermédiário',muscles:'Peitoral inferior, Triceps'},
  {id:4,name:'Crossover Polia Alta',cat:'Peito',icon:'bx-dumbbell',desc:'Crossover puxando de cima para baixo, com foco maior na parte inferior do peito.',sets:3,reps:'12-15',active:35,rest:45,diff:'Intermédiário',muscles:'Peitoral inferior'},
  {id:5,name:'Crossover Polia Média',cat:'Peito',icon:'bx-dumbbell',desc:'Crossover na linha média para contração central do peitoral.',sets:3,reps:'12-15',active:35,rest:45,diff:'Intermédiário',muscles:'Peitoral'},
  {id:6,name:'Crossover Polia Baixa',cat:'Peito',icon:'bx-dumbbell',desc:'Crossover de baixo para cima, trabalhando a regiao superior do peitoral.',sets:3,reps:'12-15',active:35,rest:45,diff:'Intermédiário',muscles:'Peitoral superior'},
  {id:7,name:'Crucifixo Reto',cat:'Peito',icon:'bx-dumbbell',desc:'Isolador de peito com halteres ou polia, feito no banco reto.',sets:3,reps:'12-15',active:35,rest:45,diff:'Iniciante',muscles:'Peitoral'},
  {id:8,name:'Crucifixo Inclinado',cat:'Peito',icon:'bx-dumbbell',desc:'Variação do crucifixo com foco na parte superior do peitoral.',sets:3,reps:'12-15',active:35,rest:45,diff:'Intermédiário',muscles:'Peitoral superior'},
  {id:9,name:'Crucifixo Declinado',cat:'Peito',icon:'bx-dumbbell',desc:'Variação do crucifixo para enfase na porcao inferior do peitoral.',sets:3,reps:'12-15',active:35,rest:45,diff:'Intermédiário',muscles:'Peitoral inferior'},
  {id:10,name:'Voador Peck Deck',cat:'Peito',icon:'bx-dumbbell',desc:'Exercicio isolado em maquina para contração do peitoral.',sets:3,reps:'12-15',active:35,rest:45,diff:'Iniciante',muscles:'Peitoral'},
  {id:11,name:'Pullover',cat:'Peito',icon:'bx-dumbbell',desc:'Movimento com halter ou barra, trabalhando peito, serratil e dorsais.',sets:3,reps:'10-12',active:35,rest:60,diff:'Intermédiário',muscles:'Peitoral, Dorsais, Serratil'},
  {id:12,name:'Flexao de Braco',cat:'Peito',icon:'bx-body',desc:'Exercicio com peso corporal para peito e triceps.',sets:3,reps:'15-20',active:45,rest:60,diff:'Iniciante',muscles:'Peitoral, Triceps, Core'},
  {id:13,name:'Flexao Diamante',cat:'Peito',icon:'bx-body',desc:'Flexao com maos proximas, aumentando o foco em triceps.',sets:3,reps:'12-15',active:35,rest:45,diff:'Intermédiário',muscles:'Triceps, Peitoral'},
  {id:14,name:'Flexao Arqueiro',cat:'Peito',icon:'bx-body',desc:'Variação avancada unilateral para peito e triceps.',sets:3,reps:'8-10/lado',active:40,rest:60,diff:'Avancado',muscles:'Peitoral, Triceps, Core'},
  {id:15,name:'Puxada Alta Aberta',cat:'Costas',icon:'bx-dumbbell',desc:'Puxada na polia alta com pegada aberta pronada, focando dorsais.',sets:4,reps:'10-12',active:40,rest:60,diff:'Intermédiário',muscles:'Dorsais, Biceps'},
  {id:16,name:'Puxada Alta Fechada',cat:'Costas',icon:'bx-dumbbell',desc:'Puxada com pegada fechada ou triangulo, boa para dorsais e meio das costas.',sets:4,reps:'10-12',active:40,rest:60,diff:'Intermédiário',muscles:'Dorsais, Biceps'},
  {id:17,name:'Puxada Supinada',cat:'Costas',icon:'bx-dumbbell',desc:'Puxada alta com pegada supinada, envolvendo bastante biceps.',sets:4,reps:'10-12',active:40,rest:60,diff:'Intermédiário',muscles:'Dorsais, Biceps'},
  {id:18,name:'Pulldown Braco Estendido',cat:'Costas',icon:'bx-dumbbell',desc:'Puxada em pe com bracos estendidos usando corda ou barra reta.',sets:3,reps:'12-15',active:35,rest:45,diff:'Intermédiário',muscles:'Dorsais'},
  {id:19,name:'Remada Curvada',cat:'Costas',icon:'bx-dumbbell',desc:'Remada com barra ou halteres para espessura das costas.',sets:4,reps:'8-12',active:40,rest:90,diff:'Intermédiário',muscles:'Dorsais, Romboides, Biceps'},
  {id:20,name:'Remada Baixa Sentada',cat:'Costas',icon:'bx-dumbbell',desc:'Remada na polia baixa com triangulo, barra reta ou corda.',sets:4,reps:'10-12',active:40,rest:60,diff:'Intermédiário',muscles:'Costas, Biceps'},
  {id:21,name:'Remada Unilateral Serrote',cat:'Costas',icon:'bx-dumbbell',desc:'Remada com halter apoiando joelho e mao no banco.',sets:4,reps:'10-12/lado',active:40,rest:60,diff:'Intermédiário',muscles:'Dorsais, Biceps'},
  {id:22,name:'Remada Cavalinho',cat:'Costas',icon:'bx-dumbbell',desc:'Remada com barra T, excelente para meio das costas.',sets:4,reps:'8-12',active:40,rest:75,diff:'Intermédiário',muscles:'Costas, Dorsais'},
  {id:23,name:'Barra Fixa Pronada',cat:'Costas',icon:'bx-dumbbell',desc:'Pull-up com pegada pronada e aberta para dorsais.',sets:4,reps:'6-10',active:40,rest:90,diff:'Avancado',muscles:'Dorsais, Biceps'},
  {id:24,name:'Barra Fixa Supinada Chin-up',cat:'Costas',icon:'bx-dumbbell',desc:'Barra fixa com pegada supinada e fechada, com maior participação do biceps.',sets:4,reps:'6-10',active:40,rest:90,diff:'Avancado',muscles:'Dorsais, Biceps'},
  {id:25,name:'Levantamento Terra',cat:'Costas',icon:'bx-dumbbell',desc:'Composto pesado para costas, lombar, posterior e gluteos.',sets:4,reps:'5-8',active:35,rest:180,diff:'Avancado',muscles:'Costas, Lombar, Posterior, Gluteos'},
  {id:26,name:'Hiperextensao Lombar',cat:'Costas',icon:'bx-body',desc:'Exercicio no banco romano para lombar e cadeia posterior.',sets:3,reps:'12-15',active:35,rest:45,diff:'Iniciante',muscles:'Lombar, Gluteos, Posterior'},
  {id:27,name:'Desenvolvimento Militar',cat:'Ombros',icon:'bx-dumbbell',desc:'Empurrar peso acima da cabeca com barra ou halteres.',sets:4,reps:'8-12',active:40,rest:75,diff:'Intermédiário',muscles:'Deltoides, Triceps'},
  {id:28,name:'Desenvolvimento com Halteres',cat:'Ombros',icon:'bx-dumbbell',desc:'Variação sentada ou em pe com halteres para ombros.',sets:4,reps:'8-12',active:40,rest:75,diff:'Intermédiário',muscles:'Deltoides, Triceps'},
  {id:29,name:'Desenvolvimento Maquina',cat:'Ombros',icon:'bx-dumbbell',desc:'Versao guiada em maquina, boa para controle e seguranca.',sets:4,reps:'10-12',active:40,rest:60,diff:'Iniciante',muscles:'Deltoides, Triceps'},
  {id:30,name:'Elevação Lateral',cat:'Ombros',icon:'bx-dumbbell',desc:'Isolamento do deltoide lateral com halteres, polia ou maquina.',sets:4,reps:'12-15',active:30,rest:45,diff:'Iniciante',muscles:'Deltoide lateral'},
  {id:31,name:'Elevação Frontal',cat:'Ombros',icon:'bx-dumbbell',desc:'Trabalha deltoide anterior com halteres, barra, anilha ou polia.',sets:4,reps:'12-15',active:30,rest:45,diff:'Iniciante',muscles:'Deltoide anterior'},
  {id:32,name:'Crucifixo Invertido',cat:'Ombros',icon:'bx-dumbbell',desc:'Posterior de ombro com halteres, polia ou voador invertido.',sets:3,reps:'12-15',active:35,rest:45,diff:'Intermédiário',muscles:'Deltoide posterior'},
  {id:33,name:'Face Pull',cat:'Ombros',icon:'bx-dumbbell',desc:'Puxada com corda para posterior de ombro e estabilidade escapular.',sets:3,reps:'15',active:35,rest:45,diff:'Intermédiário',muscles:'Deltoide posterior, Trapezio'},
  {id:34,name:'Remada Alta',cat:'Ombros',icon:'bx-dumbbell',desc:'Puxada rente ao corpo ate a linha do peito ou queixo.',sets:3,reps:'10-12',active:35,rest:60,diff:'Intermédiário',muscles:'Ombros, Trapezio'},
  {id:35,name:'Encolhimento de Ombros',cat:'Ombros',icon:'bx-dumbbell',desc:'Foco em trapezio com barra ou halteres pesados.',sets:4,reps:'12-15',active:30,rest:45,diff:'Iniciante',muscles:'Trapezio'},
  {id:36,name:'Handstand Push Up',cat:'Ombros',icon:'bx-body',desc:'Flexao invertida para ombros com peso corporal.',sets:4,reps:'6-10',active:40,rest:90,diff:'Avancado',muscles:'Ombros, Triceps'},
  {id:37,name:'Triceps Pulley Barra',cat:'Triceps',icon:'bx-dumbbell',desc:'Extensao na polia alta com barra reta ou barra V.',sets:3,reps:'12-15',active:35,rest:60,diff:'Iniciante',muscles:'Triceps'},
  {id:38,name:'Triceps Pulley Corda',cat:'Triceps',icon:'bx-dumbbell',desc:'Extensao na polia alta usando corda, com boa contração final.',sets:3,reps:'12-15',active:35,rest:60,diff:'Iniciante',muscles:'Triceps'},
  {id:39,name:'Triceps Testa',cat:'Triceps',icon:'bx-dumbbell',desc:'Extensao de triceps deitado com barra W, halteres ou polia.',sets:3,reps:'10-12',active:35,rest:60,diff:'Intermédiário',muscles:'Triceps'},
  {id:40,name:'Triceps Frances',cat:'Triceps',icon:'bx-dumbbell',desc:'Extensao acima da cabeca com halter ou polia.',sets:3,reps:'10-12',active:35,rest:45,diff:'Intermédiário',muscles:'Triceps'},
  {id:41,name:'Triceps Coice',cat:'Triceps',icon:'bx-dumbbell',desc:'Kickback com halter ou polia baixa, estendendo o braco para tras.',sets:3,reps:'12-15',active:30,rest:45,diff:'Iniciante',muscles:'Triceps'},
  {id:42,name:'Mergulho Paralela',cat:'Triceps',icon:'bx-body',desc:'Mergulho nas paralelas com foco em triceps e peitoral.',sets:4,reps:'8-12',active:40,rest:60,diff:'Avancado',muscles:'Triceps, Peitoral'},
  {id:43,name:'Supino Fechado',cat:'Triceps',icon:'bx-dumbbell',desc:'Supino com pegada fechada, excelente para triceps.',sets:4,reps:'8-10',active:40,rest:75,diff:'Intermédiário',muscles:'Triceps, Peitoral'},
  {id:44,name:'Mergulho no Banco',cat:'Triceps',icon:'bx-body',desc:'Mergulho com as maos apoiadas em banco, usando peso corporal.',sets:3,reps:'12-15',active:30,rest:45,diff:'Iniciante',muscles:'Triceps'},
  {id:45,name:'Rosca Direta',cat:'Biceps',icon:'bx-dumbbell',desc:'Flexao de cotovelo com barra reta, barra W ou polia baixa.',sets:4,reps:'10-12',active:35,rest:60,diff:'Iniciante',muscles:'Biceps'},
  {id:46,name:'Rosca Alternada',cat:'Biceps',icon:'bx-dumbbell',desc:'Rosca com halteres subindo um braco por vez.',sets:3,reps:'10-12/lado',active:35,rest:45,diff:'Iniciante',muscles:'Biceps'},
  {id:47,name:'Rosca Martelo',cat:'Biceps',icon:'bx-dumbbell',desc:'Pegada neutra com halteres ou corda, focando biceps e antebraco.',sets:4,reps:'10-12',active:35,rest:45,diff:'Iniciante',muscles:'Biceps, Antebraco'},
  {id:48,name:'Rosca Scott',cat:'Biceps',icon:'bx-dumbbell',desc:'Rosca no banco Scott com barra W, maquina ou halter unilateral.',sets:3,reps:'10-12',active:35,rest:45,diff:'Intermédiário',muscles:'Biceps'},
  {id:49,name:'Rosca Concentrada',cat:'Biceps',icon:'bx-dumbbell',desc:'Isolamento de biceps sentado com cotovelo apoiado na coxa.',sets:3,reps:'10-12',active:30,rest:45,diff:'Iniciante',muscles:'Biceps'},
  {id:50,name:'Rosca Inversa',cat:'Biceps',icon:'bx-dumbbell',desc:'Rosca com pegada pronada, ativando biceps e antebraco.',sets:3,reps:'10-12',active:35,rest:45,diff:'Intermédiário',muscles:'Antebraco, Biceps'},
  {id:51,name:'Flexao de Punho',cat:'Biceps',icon:'bx-dumbbell',desc:'Isolamento de antebraco com barra ou halteres.',sets:3,reps:'15-20',active:30,rest:30,diff:'Iniciante',muscles:'Antebraco'},
  {id:52,name:'Extensao de Punho',cat:'Biceps',icon:'bx-dumbbell',desc:'Extensao curta do punho para fortalecer antebracos.',sets:3,reps:'15-20',active:30,rest:30,diff:'Iniciante',muscles:'Antebraco'},
  {id:53,name:'Agachamento Livre',cat:'Pernas',icon:'bx-run',desc:'Agachamento com barra nas costas para quadriceps, gluteos e posterior.',sets:4,reps:'10-15',active:50,rest:120,diff:'Intermédiário',muscles:'Quadriceps, Gluteos, Posterior'},
  {id:54,name:'Agachamento Frontal',cat:'Pernas',icon:'bx-run',desc:'Front squat com barra apoiada na frente dos ombros.',sets:4,reps:'8-10',active:45,rest:90,diff:'Avancado',muscles:'Quadriceps, Core'},
  {id:55,name:'Agachamento no Smith',cat:'Pernas',icon:'bx-run',desc:'Agachamento em barra guiada, com trajeto mais controlado.',sets:4,reps:'10-12',active:45,rest:90,diff:'Intermédiário',muscles:'Quadriceps, Gluteos'},
  {id:56,name:'Agachamento Hack',cat:'Pernas',icon:'bx-run',desc:'Agachamento na maquina hack, com grande foco em quadriceps.',sets:4,reps:'10-12',active:45,rest:90,diff:'Intermédiário',muscles:'Quadriceps'},
  {id:57,name:'Leg Press 45',cat:'Pernas',icon:'bx-run',desc:'Empurrar plataforma no leg press 45 graus.',sets:4,reps:'10-15',active:45,rest:90,diff:'Intermédiário',muscles:'Quadriceps, Gluteos'},
  {id:58,name:'Leg Press Horizontal',cat:'Pernas',icon:'bx-run',desc:'Variação horizontal do leg press, boa para iniciantes.',sets:4,reps:'10-15',active:45,rest:75,diff:'Iniciante',muscles:'Quadriceps, Gluteos'},
  {id:59,name:'Cadeira Extensora',cat:'Pernas',icon:'bx-run',desc:'Isolador de quadriceps feito sentado, estendendo os joelhos.',sets:4,reps:'12-15',active:35,rest:45,diff:'Iniciante',muscles:'Quadriceps'},
  {id:60,name:'Mesa Flexora',cat:'Pernas',icon:'bx-run',desc:'Flexao de joelho deitado, focando posterior de coxa.',sets:4,reps:'12-15',active:35,rest:45,diff:'Iniciante',muscles:'Posterior'},
  {id:61,name:'Cadeira Flexora',cat:'Pernas',icon:'bx-run',desc:'Flexao de joelho sentado, trabalhando posteriores.',sets:4,reps:'12-15',active:35,rest:45,diff:'Iniciante',muscles:'Posterior'},
  {id:62,name:'Afundo',cat:'Pernas',icon:'bx-run',desc:'Passada para frente com agachamento unilateral.',sets:3,reps:'12/lado',active:35,rest:45,diff:'Intermédiário',muscles:'Quadriceps, Gluteos'},
  {id:63,name:'Passada',cat:'Pernas',icon:'bx-run',desc:'Caminhada em passadas, trabalhando pernas e equilibrio.',sets:3,reps:'12/lado',active:35,rest:45,diff:'Intermédiário',muscles:'Quadriceps, Gluteos'},
  {id:64,name:'Afundo Bulgaro',cat:'Pernas',icon:'bx-run',desc:'Unilateral com o pe de tras apoiado no banco.',sets:3,reps:'10/lado',active:40,rest:60,diff:'Intermédiário',muscles:'Quadriceps, Gluteos'},
  {id:65,name:'Stiff',cat:'Pernas',icon:'bx-dumbbell',desc:'Descida com joelhos semi-estendidos para posterior e gluteos.',sets:4,reps:'10-12',active:40,rest:75,diff:'Intermédiário',muscles:'Posterior, Gluteos'},
  {id:66,name:'Levantamento Terra Romeno',cat:'Pernas',icon:'bx-dumbbell',desc:'Variação do terra com mais foco em posterior e gluteos.',sets:4,reps:'8-12',active:40,rest:90,diff:'Intermédiário',muscles:'Posterior, Gluteos, Lombar'},
  {id:67,name:'Cadeira Adutora',cat:'Pernas',icon:'bx-run',desc:'Maquina de fechar as pernas, trabalhando parte interna da coxa.',sets:3,reps:'12-15',active:35,rest:45,diff:'Iniciante',muscles:'Adutores'},
  {id:68,name:'Good Morning',cat:'Pernas',icon:'bx-dumbbell',desc:'Movimento de dobrar o quadril, trabalhando posterior e lombar.',sets:3,reps:'12',active:35,rest:60,diff:'Intermédiário',muscles:'Posterior, Lombar'},
  {id:69,name:'Elevação Pelvica Hip Thrust',cat:'Gluteos',icon:'bx-body',desc:'Elevação do quadril com barra, principal movimento para gluteos.',sets:4,reps:'10-15',active:45,rest:75,diff:'Intermédiário',muscles:'Gluteos'},
  {id:70,name:'Agachamento Sumo',cat:'Gluteos',icon:'bx-run',desc:'Base aberta com pontas dos pes para fora, foco em gluteos e adutores.',sets:4,reps:'12',active:40,rest:60,diff:'Intermédiário',muscles:'Gluteos, Adutores'},
  {id:71,name:'Cadeira Abdutora',cat:'Gluteos',icon:'bx-run',desc:'Maquina de abrir as pernas, ativando gluteo medio.',sets:4,reps:'12-20',active:35,rest:45,diff:'Iniciante',muscles:'Gluteo medio'},
  {id:72,name:'Gluteo na Polia',cat:'Gluteos',icon:'bx-run',desc:'Coice na polia com caneleira, estendendo a perna para tras.',sets:3,reps:'12-15/lado',active:35,rest:45,diff:'Iniciante',muscles:'Gluteos'},
  {id:73,name:'Gluteo Maquina Coice',cat:'Gluteos',icon:'bx-run',desc:'Coice em maquina especifica para gluteos.',sets:3,reps:'12-15/lado',active:35,rest:45,diff:'Iniciante',muscles:'Gluteos'},
  {id:74,name:'Abducao de Quadril com Caneleira',cat:'Gluteos',icon:'bx-run',desc:'Abertura lateral da perna em pe ou deitado.',sets:3,reps:'15-20/lado',active:30,rest:30,diff:'Iniciante',muscles:'Gluteo medio'},
  {id:75,name:'Panturrilha em Pe',cat:'Panturrilhas',icon:'bx-run',desc:'Elevação na ponta dos pes em maquina, Smith ou step.',sets:4,reps:'15-20',active:35,rest:45,diff:'Iniciante',muscles:'Panturrilhas'},
  {id:76,name:'Panturrilha Sentado',cat:'Panturrilhas',icon:'bx-run',desc:'Trabalha o soleo com joelhos flexionados.',sets:4,reps:'15-20',active:35,rest:45,diff:'Iniciante',muscles:'Panturrilhas'},
  {id:77,name:'Panturrilha no Leg Press',cat:'Panturrilhas',icon:'bx-run',desc:'Usa o leg press para empurrar apenas com a ponta dos pes.',sets:4,reps:'15-20',active:35,rest:45,diff:'Iniciante',muscles:'Panturrilhas'},
  {id:78,name:'Abdominal Supra',cat:'Core',icon:'bx-body',desc:'Abdominal tradicional flexionando o tronco para cima.',sets:4,reps:'15-20',active:30,rest:30,diff:'Iniciante',muscles:'Abdomen'},
  {id:79,name:'Abdominal Infra',cat:'Core',icon:'bx-body',desc:'Elevação de pernas no solo ou joelhos na barra fixa.',sets:4,reps:'15-20',active:30,rest:30,diff:'Iniciante',muscles:'Core'},
  {id:80,name:'Abdominal Bicicleta',cat:'Core',icon:'bx-body',desc:'Obliquos com rotação do tronco alternando cotovelo e joelho.',sets:4,reps:'30',active:35,rest:30,diff:'Iniciante',muscles:'Abdomen, Obliquos'},
  {id:81,name:'Russian Twist',cat:'Core',icon:'bx-body',desc:'Rotação russa para obliquos e controle do core.',sets:4,reps:'20',active:30,rest:30,diff:'Iniciante',muscles:'Obliquos'},
  {id:82,name:'Abdominal na Polia Alta',cat:'Core',icon:'bx-dumbbell',desc:'Crunch ajoelhado com corda na polia alta.',sets:3,reps:'12-15',active:35,rest:45,diff:'Intermédiário',muscles:'Abdomen'},
  {id:83,name:'Prancha Isometrica',cat:'Core',icon:'bx-body',desc:'Prancha frontal para estabilidade do core.',sets:3,reps:'45-60s',active:60,rest:30,diff:'Iniciante',muscles:'Core, Ombros'},
  {id:84,name:'Prancha Lateral',cat:'Core',icon:'bx-body',desc:'Prancha lateral para obliquos e estabilidade.',sets:3,reps:'30-45s/lado',active:45,rest:20,diff:'Iniciante',muscles:'Core, Obliquos'},
  {id:85,name:'Roda Abdominal',cat:'Core',icon:'bx-body',desc:'Ab wheel, rolando para frente e voltando com controle.',sets:3,reps:'8-12',active:35,rest:60,diff:'Avancado',muscles:'Core'},
  {id:86,name:'Abdominal Canivete',cat:'Core',icon:'bx-body',desc:'Core completo elevando tronco e pernas simultaneamente.',sets:4,reps:'15',active:35,rest:30,diff:'Intermédiário',muscles:'Abdomen'},
  {id:87,name:'Superman',cat:'Core',icon:'bx-body',desc:'Fortalecimento lombar deitado, elevando bracos e pernas.',sets:3,reps:'15',active:30,rest:30,diff:'Iniciante',muscles:'Lombar'},
  {id:88,name:'Esteira Caminhada',cat:'Cardio',icon:'bx-run',desc:'Cardio leve/moderado na esteira.',sets:1,reps:'20-40min',active:1800,rest:0,diff:'Iniciante',muscles:'Cardiovascular'},
  {id:89,name:'Corrida Aerobica',cat:'Cardio',icon:'bx-run',desc:'Corrida continua para resistencia cardiovascular.',sets:1,reps:'20min',active:1200,rest:0,diff:'Iniciante',muscles:'Cardiovascular'},
  {id:90,name:'Bike Ergometrica',cat:'Cardio',icon:'bx-run',desc:'Cardio de baixo impacto na bicicleta.',sets:1,reps:'30min',active:1800,rest:0,diff:'Iniciante',muscles:'Cardio'},
  {id:91,name:'Eliptico Transport',cat:'Cardio',icon:'bx-run',desc:'Cardio com baixo impacto para corpo inteiro.',sets:1,reps:'25min',active:1500,rest:0,diff:'Iniciante',muscles:'Corpo inteiro, Cardio'},
  {id:92,name:'Simulador de Escada',cat:'Cardio',icon:'bx-run',desc:'Stairmaster para condicionamento e membros inferiores.',sets:1,reps:'15-25min',active:1200,rest:0,diff:'Intermédiário',muscles:'Cardio, Gluteos, Pernas'},
  {id:93,name:'Polichinelo',cat:'Cardio',icon:'bx-run',desc:'Aquecimento dinamico e cardio simples.',sets:3,reps:'1min',active:60,rest:20,diff:'Iniciante',muscles:'Cardiovascular'},
  {id:94,name:'Escalador',cat:'Cardio',icon:'bx-run',desc:'Mountain climber para cardio e core.',sets:4,reps:'40s',active:40,rest:20,diff:'Intermédiário',muscles:'Core, Cardio'},
  {id:95,name:'Pular Corda',cat:'Cardio',icon:'bx-run',desc:'Condicionamento com corda tradicional.',sets:5,reps:'1min',active:60,rest:30,diff:'Iniciante',muscles:'Cardio'},
  {id:96,name:'Sprint',cat:'Cardio',icon:'bx-run',desc:'Tiros curtos de alta intensidade.',sets:8,reps:'30s',active:30,rest:60,diff:'Avancado',muscles:'Pernas, Cardio'},
  {id:97,name:'Burpee',cat:'Funcional',icon:'bx-run',desc:'Movimento intenso de corpo inteiro.',sets:4,reps:'10-15',active:45,rest:60,diff:'Avancado',muscles:'Corpo inteiro'},
  {id:98,name:'Box Jump',cat:'Funcional',icon:'bx-run',desc:'Salto na caixa para explosao de pernas.',sets:4,reps:'12',active:30,rest:60,diff:'Avancado',muscles:'Pernas'},
  {id:99,name:'Kettlebell Swing',cat:'Funcional',icon:'bx-dumbbell',desc:'Balanco com kettlebell para potencia e cardio.',sets:4,reps:'20',active:40,rest:45,diff:'Intermédiário',muscles:'Posterior, Core'},
  {id:100,name:'Corda Naval',cat:'Funcional',icon:'bx-run',desc:'Ondas com corda naval para condicionamento intenso.',sets:5,reps:'30s',active:30,rest:30,diff:'Intermédiário',muscles:'Corpo inteiro'},
  {id:101,name:'Farmer Walk',cat:'Funcional',icon:'bx-dumbbell',desc:'Caminhada do fazendeiro para pegada e core.',sets:4,reps:'40m',active:45,rest:60,diff:'Intermédiário',muscles:'Antebraco, Core'},
  {id:102,name:'Clean and Press',cat:'Funcional',icon:'bx-dumbbell',desc:'Movimento olimpico com puxada e desenvolvimento.',sets:4,reps:'6-8',active:45,rest:120,diff:'Avancado',muscles:'Corpo inteiro'},
  {id:103,name:'Wall Sit',cat:'Pernas',icon:'bx-run',desc:'Isometria sentado na parede para resistencia de quadriceps.',sets:4,reps:'60s',active:60,rest:30,diff:'Iniciante',muscles:'Quadriceps'}
];

const FOODS = [
  {id:1,name:'Peito de Frango grelhado (100g)',cal:165,prot:31,carb:0,fat:3.6},
  {id:2,name:'Arroz branco cozido (100g)',cal:130,prot:2.7,carb:28,fat:0.3},
  {id:3,name:'Feijao carioca cozido (100g)',cal:77,prot:4.8,carb:14,fat:0.5},
  {id:4,name:'Ovo cozido',cal:78,prot:6,carb:0.6,fat:5},
  {id:5,name:'Banana prata',cal:89,prot:1.1,carb:23,fat:0.3},
  {id:6,name:'Batata-doce cozida',cal:86,prot:1.6,carb:20,fat:0.1},
  {id:7,name:'Aveia em flocos',cal:147,prot:5,carb:25,fat:2.5},
  {id:8,name:'Leite desnatado',cal:69,prot:6.8,carb:9.6,fat:0.4},
  {id:9,name:'Iogurte grego',cal:100,prot:9,carb:4,fat:5},
  {id:10,name:'Salmao grelhado',cal:208,prot:20,carb:0,fat:13},

  {id:11,name:'Brocolis cozido',cal:34,prot:2.8,carb:7,fat:0.4},
  {id:12,name:'Whey Protein',cal:120,prot:24,carb:4,fat:1.5},
  {id:13,name:'Pao integral',cal:69,prot:3.6,carb:12,fat:1},
  {id:14,name:'Maca',cal:52,prot:0.3,carb:14,fat:0.2},
  {id:15,name:'Amendoim torrado',cal:176,prot:7,carb:5,fat:15},
  {id:16,name:'Atum em água',cal:128,prot:28,carb:0,fat:1},
  {id:17,name:'Arroz integral',cal:124,prot:2.6,carb:26,fat:1},
  {id:18,name:'Peito de Peru',cal:118,prot:24,carb:1,fat:1.8},
  {id:19,name:'Pasta de Amendoim',cal:188,prot:8,carb:6,fat:16},
  {id:20,name:'Batata inglesa',cal:87,prot:1.9,carb:20,fat:0.1},

  {id:21,name:'Queijo cottage',cal:98,prot:11,carb:3.4,fat:4.3},
  {id:22,name:'Ervilha cozida',cal:84,prot:5.4,carb:15,fat:0.4},
  {id:23,name:'Lentilha cozida',cal:116,prot:9,carb:20,fat:0.4},
  {id:24,name:'Abacate',cal:160,prot:2,carb:9,fat:14.7},
  {id:25,name:'Coxa de Frango',cal:185,prot:26,carb:0,fat:8.9},
  {id:26,name:'Tilapia grelhada',cal:129,prot:26,carb:0,fat:2.7},
  {id:27,name:'Sardinha',cal:208,prot:25,carb:0,fat:11},
  {id:28,name:'Carne bovina magra',cal:217,prot:26,carb:0,fat:12},
  {id:29,name:'Patinho moido',cal:219,prot:26,carb:0,fat:12},
  {id:30,name:'Tofu',cal:76,prot:8,carb:2,fat:4.8},

  {id:31,name:'Grao de bico',cal:164,prot:9,carb:27,fat:2.6},
  {id:32,name:'Macarrao integral',cal:124,prot:5,carb:25,fat:1.1},
  {id:33,name:'Quinoa',cal:120,prot:4.4,carb:21,fat:1.9},
  {id:34,name:'Chia',cal:486,prot:17,carb:42,fat:31},
  {id:35,name:'Linhaca',cal:534,prot:18,fat:42,carb:29},
  {id:36,name:'Castanha do Para',cal:656,prot:14,carb:12,fat:66},
  {id:37,name:'Castanha de Caju',cal:553,prot:18,carb:30,fat:44},
  {id:38,name:'Nozes',cal:654,prot:15,carb:14,fat:65},
  {id:39,name:'Amendoa',cal:579,prot:21,carb:22,fat:49},
  {id:40,name:'Iogurte natural',cal:61,prot:3.5,carb:4.7,fat:3.3},

  {id:41,name:'Queijo minas',cal:264,prot:17,carb:3,fat:21},
  {id:42,name:'Ricota',cal:174,prot:11,carb:3,fat:13},
  {id:43,name:'Mandioca cozida',cal:125,prot:1,carb:30,fat:0.3},
  {id:44,name:'Inhame cozido',cal:118,prot:1.5,carb:28,fat:0.2},
  {id:45,name:'Milho cozido',cal:96,prot:3.4,carb:21,fat:1.5},
  {id:46,name:'Tomate',cal:18,prot:0.9,carb:3.9,fat:0.2},
  {id:47,name:'Alface',cal:15,prot:1.4,carb:2.9,fat:0.2},
  {id:48,name:'Cenoura',cal:41,prot:0.9,carb:10,fat:0.2},
  {id:49,name:'Pepino',cal:15,prot:0.7,carb:3.6,fat:0.1},
  {id:50,name:'Beterraba',cal:43,prot:1.6,carb:10,fat:0.2},

  {id:51,name:'Laranja',cal:47,prot:0.9,carb:12,fat:0.1},
  {id:52,name:'Mamao',cal:43,prot:0.5,carb:11,fat:0.3},
  {id:53,name:'Manga',cal:60,prot:0.8,carb:15,fat:0.4},
  {id:54,name:'Morango',cal:32,prot:0.7,carb:7.7,fat:0.3},
  {id:55,name:'Uva',cal:69,prot:0.7,carb:18,fat:0.2},
  {id:56,name:'Pera',cal:57,prot:0.4,carb:15,fat:0.1},
  {id:57,name:'Kiwi',cal:61,prot:1.1,carb:15,fat:0.5},
  {id:58,name:'Abacaxi',cal:50,prot:0.5,carb:13,fat:0.1},
  {id:59,name:'Melancia',cal:30,prot:0.6,carb:8,fat:0.2},
  {id:60,name:'Melao',cal:34,prot:0.8,carb:8,fat:0.2},

  {id:61,name:'Cafe preto',cal:2,prot:0.3,carb:0,fat:0},
  {id:62,name:'Cha verde',cal:1,prot:0,carb:0,fat:0},
  {id:63,name:'Água de coco',cal:19,prot:0.7,carb:3.7,fat:0.2},
  {id:64,name:'Suco de laranja natural',cal:45,prot:0.7,carb:10,fat:0.2},
  {id:65,name:'Tapioca',cal:130,prot:0,carb:32,fat:0},
  {id:66,name:'Panqueca proteica',cal:210,prot:18,carb:20,fat:6},
  {id:67,name:'Hamburguer caseiro',cal:250,prot:22,carb:5,fat:15},
  {id:68,name:'Pizza fit',cal:190,prot:15,carb:18,fat:7},
  {id:69,name:'Omelete',cal:154,prot:11,carb:1,fat:11},
  {id:70,name:'Clara de ovo',cal:17,prot:3.6,carb:0.2,fat:0},

  {id:71,name:'Barrinha proteica',cal:190,prot:15,carb:18,fat:6},
  {id:72,name:'Granola',cal:471,prot:10,carb:64,fat:20},
  {id:73,name:'Mel',cal:304,prot:0.3,carb:82,fat:0},
  {id:74,name:'Chocolate 70%',cal:598,prot:7.8,carb:46,fat:43},
  {id:75,name:'Pipoca sem oleo',cal:31,prot:1,carb:6,fat:0.4},
  {id:76,name:'Cuscuz',cal:112,prot:3.8,carb:23,fat:0.2},
  {id:77,name:'Pao frances',cal:135,prot:4.5,carb:28,fat:1.5},
  {id:78,name:'Requeijao light',cal:54,prot:3,carb:1,fat:4},
  {id:79,name:'Frango desfiado',cal:150,prot:29,carb:0,fat:3},
  {id:80,name:'Shake proteico',cal:220,prot:30,carb:15,fat:4}
];

const MEAL_CFG = [
  {key:'breakfast',label:'Cafe da manha',icon:'bx-coffee',color:'var(--amber)'},
  {key:'lunch',label:'Almoco',icon:'bxs-bowl-hot',color:'var(--accent)'},
  {key:'snack',label:'Lanche',icon:'bx-food-tag',color:'var(--blue)'},
  {key:'dinner',label:'Jantar',icon:'bx-moon',color:'var(--purple)'}
];

const TIPS = [
  'Beba água ao acordar.',
  'Treine pelo menos 30 minutos por dia.',
  'Durma entre 7 e 9 horas.',
  'Consuma proteínas em todas as refeições.',
  'Evite ultraprocessados.',
  'Mantenha uma rotina consistente.',
  'Treino e descanso sao igualmente importantes.',
  'Alongamento ajuda na recuperação muscular.',
  'Hidratação melhora desempenho.',
  'Faca refeições equilibradas.'
];

const GOAL_LABELS = {
  perda_peso:'Perder Peso',
  manutencao:'Manter Peso',
  ganho_massa:'Ganhar Massa',
  saude_geral:'Saúde Geral'
};

const DAY_NAMES = ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'];

const DIFF_BADGE = {
  Iniciante:'badge-green',
  Intermédiário:'badge-blue',
  Avancado:'badge-red'
};

const SCORE_COLOR = s => s >= 80 ? 'var(--accent)' : s >= 50 ? 'var(--amber)' : 'var(--red)';

const EX_CATS = ['Todos', ...new Set(EX.map(e => e.cat))];
